# This Deployment Manifest is not parameterized so you'll need to update the app label, 
# container image and name in order for your azure pipelines deployment to succeed
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spacy-extractor
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spacy-extractor
    spec:
      containers:
      - name: spacy-extractor
        image: yourContainerRegistryName.azurecr.io/spacyextractor
        imagePullPolicy: Always
        resources:
          requests:
            memory: 0.1G
            cpu: 0.1
          limits:
            memory: 0.5G
            cpu: 0.5
        ports:
        - name: http-api
          containerPort: 8080
        env:
        - name: CLUSTER_ROUTE_PREFIX
          value: /spacy/
