# This service assumes you're using Ambassador as an API Gateway.
# See https://getambassador.io for more info on setting up Ambassador with Kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: spacy-extractor
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: spacy-extractor-mapping
      prefix: /spacy/
      service: spacy-extractor
      timeout_ms: 20000
      bypass_auth: true
spec:
  selector:
    app: spacy-extractor
  ports:
    - port: 80
      targetPort: http-api
      name: http
    - port: 443
      targetPort: http-api
      name: https
  type: ClusterIP