name: Scrapy Yahoo Data Usd
on:
  push:
    branches:
      - 'main'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 8-20 * * 1-5'

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_STOCK_NEW_RELEASE_WEBHOOK }}
# Add cron job to ensure external webpages + apis have no changed
jobs:
  scrap_data:
    runs-on: ubuntu-latest
    name: coverage
    env:
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install -r nlp_articles/requirements/scrapy.txt
          python -m pip install -r nlp_articles/requirements/spacy.txt
          spacy download en_core_web_sm

      - name: Crawl
        run:  |
         scrapy crawl usd_stock_news

      - name: Commit files
        run: |
          if [[ -z $(git status -s) ]]
          then
            echo "tree is clean"
          else
            git add *.txt || true
            git add *.csv || true
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            echo "tree is dirty, please commit changes before running this"
            echo "PUSH_FILES=true" >> $GITHUB_ENV
            git config pull.rebase true || true
            git pull origin main --strategy=ours || true
            git pull origin main || true
<<<<<<< Updated upstream
=======
            git commit -m "Add changes" -a || true
>>>>>>> Stashed changes
          fi
      - name: Test
        run: echo ${{ env.PUSH_FILES }}

      - name: Push changes
        if: ${{ env.PUSH_FILES == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
